#!/bin/bash

# 把 DASK_DASHBOARD_URL 替换成 JupyterHub 代理地址
sed -i -e "s|DASK_DASHBOARD_URL|${JUPYTERHUB_BASE_URL}user/${JUPYTERHUB_USER}/proxy/8787|g" binder/jupyterlab-workspace.json
export DASK_DISTRIBUTED__DASHBOARD__LINK="${JUPYTERHUB_SERVICE_PREFIX}proxy/{port}/status"

# 导入 JupyterLab workspace
jupyter lab workspaces import binder/jupyterlab-workspace.json

export DASK_TUTORIAL_SMALL=1

exec "$@"
